### ISSUE TITLE
PROTOTIPO

### ISSUE THREAD

**Issue by Luftwaffe-boy** [SistemasTecTlaxiaco/actividad-9-practica-de-proyecto-de-ra-equipo-irving-1#1]
[ProyectoRA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-proyecto-de-ra-equipo-irving-1/files/15196446/ProyectoRA.pdf)

**Comment by MariaJose-1007** [comment]
EXCELENTE 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
